config/routes.rb
RailsApp::Application.routes.draw do
  devise_for :users
  root to: 'welcome#index'

  TheRoleManagementPanel::Routes.mixin(self)

  get 'welcome/index'
  get 'welcome/profile'

  get 'autologin'         => 'welcome#autologin', as: :autologin
  put 'users/change_role' => "users#change_role", as: :user_change_role

  resources  :users, only: [:edit, :update]

  resources  :pages do
    collection do
      get :my
      get :manage
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
  # RELATIONS
  belongs_to :user

  # VALIDATIONS
  validates :user,    presence: true
  validates :title,   presence: true, uniqueness: true
  validates :content, presence: true

  scope :with_state, ->(states) { where state: Array.wrap(states) }
end

app/models/role.rb
class Role < ApplicationRecord
  include TheRole::Api::Role

  # PostgresSQL: :json column patch
  # MIGRATION file: | t.column :the_role, :json, null: false |
  #
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #
  # def _jsonable val
  #   val.is_a?(Hash) ? val : JSON.load(val)
  # end

  # def to_hash
  #   begin the_role rescue {} end
  # end

  # def to_json
  #   the_role.is_a?(Hash) ? the_role.to_json : the_role
  # end
  #
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
end

app/models/user.rb
class User < ApplicationRecord
  include TheRole::Api::User

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :email, :password, :password_confirmation, :remember_me
  # User accessible fields
  # attr_accessible :name, :company, :address

  # When we uncomment this string - test should give fail
  # just for example, do not uncomment it
  # attr_accessible :some_protected_field

  # RELATIONS
  has_many :pages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include TheRole::Controller

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protect_from_forgery
  before_action :set_locale

  private

  def set_locale
    locale = 'en'
    langs  = %w{ en ru es pl zh_CN }

    if params[:locale]
      lang = params[:locale]
      if langs.include? lang
        locale           = lang
        cookies[:locale] = lang
      end
    else
      if cookies[:locale]
        lang   = cookies[:locale]
        locale = lang if langs.include? lang
      end
    end

    I18n.locale = locale
    redirect_back(fallback_location: root_path) if params[:locale]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :login_required, except: [:index, :show]
  before_action :role_required,  except: [:index, :show]

  # !!! ATTENTION !!!
  #
  # TheRole: You have to set object for ownership check
  # before check ownership via `owner_required` method
  # You can do it with `for_ownership_check(@page)` in `set_page`
  #
  before_action :set_page,       only: [:edit, :update, :destroy]
  before_action :owner_required, only: [:edit, :update, :destroy]

  # Public

  def index
    @pages = Page.with_state(:published).all
  end

  def show
    @page = Page.with_state(:published).find params[:id]
  end

  # Login && role

  def new
    @page = Page.new
  end

  def create
    @page = Page.new page_params

    if @page.save
      redirect_to @page, notice: 'Page was successfully created.'
    else
      render action: 'new'
    end
  end

  def my
    @pages = current_user.pages
  end

  # login && role && ownership

  def edit; end

  def update
    if @page.update_attributes page_params
      redirect_to @page, notice: 'Page was successfully updated.'
    else
      render action: :edit
    end
  end

  def destroy
    @page.destroy
    redirect_to pages_url
  end

  # Admin or Pages Moderator Role require

  def manage
    @pages = Page.all
  end

  private

  def set_page
    @page = Page.find params[:id]

    # TheRole: object for ownership checking
    for_ownership_check(@page)
  end

  def page_params
    params.require(:page).permit(:user_id, :title, :content, :state)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_required
  before_action :role_required

  before_action :find_user,      :only => [:edit, :update]
  before_action :owner_required, :only => [:edit, :update]

  def edit; end

  def update
    @user.update_attributes params[:user]
    flash[:notice] = 'User was successfully updated.'
    redirect_to edit_user_path @user
  end

  def change_role
    @user = User.find params[:user_id]
    @role = Role.find params[:role_id]
    @user.update_attribute(:role, @role)
    redirect_to edit_user_path @user
  end

  private

  def find_user
    @user = User.find params[:id]

    # TheRole: You have to define object for ownership check
    for_ownership_check(@user)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # before_filter :authenticate_user!, :except => [:index, :autologin]
  before_action :login_required, :except => [:index, :autologin]

  def index; end
  def profile; end

  def autologin
    user = User.find_by_email params[:email]
    sign_in user if user
    redirect_to request.referrer || root_path
  end

end

app/views/layouts/_current_user_info.html.haml
%h2 Current user

%p
  - if user_signed_in?
    %p
      %b{ style: "color:green" }= current_user.name
    %p
      %i role: #{current_user.role.name}
      \|
      = link_to "Sign out", destroy_user_session_path, :method => :delete
  - else
    %p
      %i Guest
    %p
      = link_to "Sign in", new_user_session_path
      \|
      = link_to "Sign up", new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TheRoleTestcase
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = stylesheet_link_tag "http://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css"

    = csrf_meta_tags

    = yield :js
    = yield :css

  %body
    .container
      .row
        .col-md-12.header

          %hr

          %p{ style: "text-align:center" }
            Authorization gem for Ruby on Rails with Management Panel

          %p{ style: "text-align:center" }
            = link_to "https://github.com/the-teacher/the_role" do
              = image_tag "https://raw.githubusercontent.com/TheRole/docs/master/images/the_role.png", alt: 'TheRole 3.0', width: 150

          %p{ style: "text-align:center" }
            Semantic. Flexible. Lightweigh

          %hr

      .row
        .col-md-3.manage_panel
          %h4 Basic links

          %ul
            %li= link_to 'Home',         root_path
            %li= link_to 'pages/index',  pages_path
            %li= link_to 'pages/manage', manage_pages_path
            %li= link_to 'pages/my',     my_pages_path
            %li= link_to 'admin/roles',  admin_roles_path
            %li ____
            %li= link_to 'admin/roles (js)', admin_roles_path, remote: true

          = render :partial => 'layouts/current_user_info'

        .col-md-9.main_content
          = render partial: 'the_notification/flash', locals: { format: :json }
          = yield

      %hr

      .row
        .col-md-3
          %p
            = link_to 'TheRole 3', 'https://github.com/the-teacher/the_role'
        .col-md-9
          %p
            = link_to 'en', '/?locale=en'
            \|
            = link_to 'ru', '/?locale=ru'
            \|
            = link_to 'es', '/?locale=es'
            \|
            = link_to 'zh_CN', '/?locale=zh_CN'
            \|
            = link_to 'pl', '/?locale=pl'
            \|
            %b
              = t '.current_locale'
              = I18n.locale

app/views/pages/_form.html.haml
= form_for @page do |f|
  -if @page.errors.any?
    #error_explanation
      %h2= "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      %ul
        - @page.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/pages/edit.html.haml
%h1 Editing page

= render 'form'

= link_to 'Show', @page
\|
= link_to 'Back', pages_path

app/views/pages/index.html.haml
%p= link_to 'Back', root_path

%h1 Listing of #{@pages.count} pages

%table
  %tr
    %th Num
    %th User
    %th Title
    %th State
    %th
    %th
    %th

  - @pages.each_with_index do |page, index|
    %tr
      %td
        - if current_user and current_user.owner?(page)
          %span{ style: "color:red" }= index.next
        - else
          = index.next
      %td= page.user_id
      %td= page.title
      %td= page.state
      %td= link_to 'Show', page
      %td= link_to 'Edit', edit_page_path(page)
      %td= link_to 'Destroy', page, :data => { :confirm => 'Are you sure?' }, :method => :delete

app/views/pages/manage.html.haml
%p= link_to 'Back', root_path

%h1 Listing of #{@pages.count} pages

%table
  %tr
    %th Num
    %th User
    %th Title
    %th State
    %th
    %th
    %th

  - @pages.each_with_index do |page, index|
    %tr
      %td= index.next
      %td= page.user_id
      %td= page.title
      %td= page.state
      %td= link_to 'Show', page
      %td= link_to 'Edit', edit_page_path(page)
      %td= link_to 'Destroy', page, :data => { :confirm => 'Are you sure?' }, :method => :delete

app/views/pages/my.html.haml
%p= link_to 'Back', root_path
%h1 Current user: #{current_user.name}

%h2 User's pages

%ol
  - @pages.each do |page|
    %li
      %i user_id: #{page.user_id}
      %b= page.title

app/views/pages/new.html.haml
%h1 New page

= render 'form'

= link_to 'Back', pages_path

app/views/pages/show.html.haml
%p#notice= notice

%p
  %b User:
  = @page.user_id
%p
  %b Title:
  = @page.title
%p
  %b Content:
  = @page.content

= link_to 'Edit', edit_page_path(@page)
\|
= link_to 'Back', pages_path

app/views/users/edit.html.haml
- if flash[:notice]
  %p{ :style => 'background: LightGreen; padding: 10px;' }= flash[:notice]

%h2{ :style => 'color: gray' } Editable User: #{@user.name} | Role: #{@user.role.name}
%h3{ :style => 'color: lightGray' } Current User: #{current_user.name} | Role: #{current_user.role.name}

%p= link_to 'To index page', '/'

= form_for @user, :method => :put do |f|
  .field
    %p= f.label :name
    %p= f.text_field :name

  .field
    %p= f.label :email
    %p= f.text_field :email

  .field
    %p= f.label :role_id, 'Protected field'
    %p= f.text_field :role_id

  .field
    %p= f.label :some_protected_field, 'Protected field'
    %p= f.text_field :some_protected_field

  .field
    %p= f.submit


- if current_user.admin?
  = form_tag user_change_role_path, :method => :put do
    = hidden_field_tag :user_id, @user.id
    = select_tag :role_id, options_for_select(Role.all.collect{ |r| [r.name, r.id] })
    = submit_tag

app/views/welcome/index.html.haml
%h1 Users info

%ol
  - User.all.each do |user|
    %li
      %b= user.name
      \-
      - if user.role
        %b role: #{user.role.name}
      - else
        %b User has not role
      \-
      |
      = link_to 'Login now!', autologin_path(:email => user.email)
%p
  %b password:
  %i qwerty

%h1 Edit Users

%ol
  - User.all.each do |user|
    - if user.role
      %li= link_to "Edit user: #{user.name} [#{user.role.name}]",  edit_user_path(user)
    - else
      %li User #{user.name} has not role

%h1 Roles info

%ol
  - Role.all.each do |role|
    %li
      %b= role.name
      \-
      %i= role.description
      \-
      - users_list = role.users.map(&:name).join(', ')
      %b users: [#{users_list}]

app/views/welcome/profile.html.haml
%h1 Welcome#profile
%p Find me in app/views/welcome/profile.html.haml